export default {
  SET_LOGGED: 'SET_LOGGED',
  SET_PHONE: 'SET_PHONE',
  SET_EIXO: 'SET_EIXO',
  SET_ORIGIN: 'SET_ORIGIN',
  SET_DESTINATION: 'SET_DESTINATION',
  SET_AVALIATION: 'SET_AVALIATION',
};
